from app.modules.rag.services.generation_service import GenerationService


class FakeLLM:

    def generate(self, prompt: str) -> str:
        print("\n===== PROMPT SENT TO LLM =====\n")
        print(prompt)

        return "This is a test answer generated by the fake LLM."


llm = FakeLLM()

generation_service = GenerationService(llm)


query = "What is the purpose of meditation?"

context = """
Paper ID: example-paper
Chunk: 24

Meditation is described as a way to refine and use
the energy generated through the practice.
"""


answer = generation_service.generate(
    query=query,
    context=context,
)


print("\n===== GENERATED ANSWER =====\n")
print(answer)