"""add research paper metadata

Revision ID: 45feff6d63e4
Revises: da15a3119fbb
Create Date: 2026-09-11 12:01:04.497959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45feff6d63e4'
down_revision: Union[str, Sequence[str], None] = 'da15a3119fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('semantic_scholar_id', sa.String(length=100), nullable=True))
    op.add_column('papers', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('publication_year', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('citation_count', sa.Integer(), nullable=False,server_default='0'))
    op.add_column('papers', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('papers', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'papers', ['semantic_scholar_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='unique')
    op.drop_column('papers', 'pdf_url')
    op.drop_column('papers', 'source_url')
    op.drop_column('papers', 'citation_count')
    op.drop_column('papers', 'publication_year')
    op.drop_column('papers', 'authors')
    op.drop_column('papers', 'abstract')
    op.drop_column('papers', 'semantic_scholar_id')
    # ### end Alembic commands ###
