"""add knowledge graph tables

Revision ID: b2ee2554205b
Revises: 45feff6d63e4
Create Date: 2026-09-29 05:58:16.332779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ee2554205b'
down_revision: Union[str, Sequence[str], None] = '45feff6d63e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Enum('PAPER', 'CLAIM', 'METHOD', 'DATASET', 'METRIC', 'TOPIC', name='knowledgenodetype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_nodes_entity_id', 'knowledge_nodes', ['entity_id'], unique=False)
    op.create_index('ix_knowledge_nodes_node_type', 'knowledge_nodes', ['node_type'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('USES', 'STUDIES', 'SUPPORTS', 'CONTRADICTS', 'EVALUATES_WITH', 'RELATED_TO', name='knowledgerelationshiptype'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('source_paper_id', sa.UUID(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_edges_relationship_type', 'knowledge_edges', ['relationship_type'], unique=False)
    op.create_index('ix_knowledge_edges_source_node_id', 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index('ix_knowledge_edges_source_paper_id', 'knowledge_edges', ['source_paper_id'], unique=False)
    op.create_index('ix_knowledge_edges_target_node_id', 'knowledge_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_edges_target_node_id', table_name='knowledge_edges')
    op.drop_index('ix_knowledge_edges_source_paper_id', table_name='knowledge_edges')
    op.drop_index('ix_knowledge_edges_source_node_id', table_name='knowledge_edges')
    op.drop_index('ix_knowledge_edges_relationship_type', table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index('ix_knowledge_nodes_node_type', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_entity_id', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
