"""add unique constraint to paper chunks

Revision ID: da15a3119fbb
Revises: 162a2f9e8714
Create Date: 2026-08-31 15:18:04.515742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da15a3119fbb'
down_revision: Union[str, Sequence[str], None] = '162a2f9e8714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_paper_chunks_paper_id_chunk_index', 'paper_chunks', ['paper_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paper_chunks_paper_id_chunk_index', 'paper_chunks', type_='unique')
    # ### end Alembic commands ###
